#!/usr/bin/env bash

# Check if the number of parameters is less than 4
if [ $# -lt 4 ];
then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# Transfer the file to the user's home directory on the server
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
