#!/usr/bin/env bash
# This script configures NGINX web server by removing the default site
# configuration and creating a symbolic link to another configuration
# file, then restarting the NGINX service.

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
