#!/usr/bin/env bash
# This script configures NGINX web server by removing the default site
# configuration and creating a symbolic link to another configuration
# file, then restarting the NGINX service.

# Remove the default NGINX site configuration file
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the custom site configuration file
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart NGINX to apply the changes
service nginx restart
