#!/usr/bin/env bash
# 
# This script symlinks the NGINX configuration files, restarts NGINX, and
# ensures only one NGINX process is running.

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
