#!/usr/bin/env bash
#
# Infinite Loop Script with Signal Traps
# This script creates a PID file, runs an infinite loop, and sets up signal traps.
#

# Create PID file and write script's PID into it
sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2

    # Set up signal traps
    trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done
