#!/usr/bin/env bash
#
# FizzBuzz Script
# This script prints Fizz for numbers divisible by 3, Buzz for numbers
# divisible by 5, FizzBuzz for numbers divisible by both 3 and 5, and the
# number itself for other cases.
#

# Loop through numbers from 1 to 100
for num in {1..100}
do
    # Check if the number is divisible by both 3 and 5
    if ((num % 3 == 0 && num % 5 == 0))
    then
        echo "FizzBuzz"
    # Check if the number is divisible by 3
    elif ((num % 3 == 0))
    then
        echo "Fizz"
    # Check if the number is divisible by 5
    elif ((num % 5 == 0))
    then
        echo "Buzz"
    # Print the number itself for other cases
    else
        echo "$num"
    fi
done
