#!/usr/bin/env bash
# Script displays "Best School" 10 times.
# At the 9th iteration, it displays Best School and then Hi

ITERATION=0
while [ $ITERATION -lt 11 ]
do
    if [ $ITERATION -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ITERATION=$(( ITERATION + 1 ))
done
