#!/usr/bin/env bash

# Iterate over files in the current directory
for file in *;
do
    # Check if the item is a file (not a directory)
    if [ -f "$file" ]; then
        # Extract the second field from the file name using '-' as the delimiter
        second_field=$(echo "$file" | cut -d '-' -f2)
        
        # Display the result
        echo "$second_field"
    fi
done
