#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2 and
# facebook.com resolves to 8.8.8.8

sudo tee /etc/hosts > /dev/null <<EOF
127.0.0.2          localhost
8.8.8.8            facebook.com
EOF
